services:
  calc:
    build:
      context: .
    container_name: calculator
    ports:
      - "10000:10000"
    networks:
      - bombay
  
  nginx:
    image:nginx:latest
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    ./nginx.conf:/etc/nginx/conf.d/proxy.conf
  networks: 
    - bombay